# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 072e108a88f6d0bc5ef03b5acee1a3b5adcd0611124d91ffb575f1172a8595ec6f4c941e8f67cb110df6b3288f3e59adeaf42737c5f6e6bf41477b33d13ea19b

test:
  secret_key_base: 0c5e0603ac99032186492788944931136a5082772be230df6b584c2e9360bd07c3c82ce7a85affbcc4c7f9dcef67c1f4128b9723e45bee7b64656a88e33c95a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
